server:
  port: 10002
  
eureka:
  client:
    service-url:
      #表示注册到 hyr-eureka-server 的地址
      defaultZone: http://localhost:10000/eureka/
spring:
  profiles:
    active: dev
  application:
    #表示注册到eureka的服务名
    name: gateway
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:10005
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          lowerCaseServiceId: true #将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了）
      default-filters:
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
            #- Header=token, \d+  #当请求的Header中有token的header名，且header值为数字时，请求会被路由到配置的 uri. 
          filters:
            - StripPrefix=1 # 去除请求地址中的to_client
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
          
       
